name: Build dns2tcp for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Build dns2tcp
        run: |
          git clone https://github.com/your/dns2tcp.git
          cd dns2tcp
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dns2tcp-windows
          path: dns2tcp/dns2tcp.exe
