name: Build dns2tcp for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install MinGW
        run: |
          choco install mingw -y

      - name: Install dependencies
        run: |
          mingw32-make -f Makefile.win32

      - name: Build dns2tcp
        run: |
          mingw32-make -f Makefile.win32 all

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dns2tcp-windows
          path: dns2tcp.exe